### ISSUE TITLE
Error when downloading jq

### ISSUE THREAD

**Issue by caleb15** [CircleCI-Public/jq-orb#10]
> curl: (22) The requested URL returned error: 403 rate limit exceeded

I'm guessing the rate limit for downloading from the github API was exceeded because of so many people using the jq orb.

**Comment by felicianotech** [comment]
We're looking into this now. Thank you for reporting.

**Comment by caleb15** [comment]
Thanks for the fast response, I appreciate it.

**Comment by felicianotech** [comment]
You're welcome. The orb didn't actually publish until this morning. The new orb that won't have this GitHub API issue was published as v2.0.0.
