### ISSUE TITLE
Failing because /bin/sh is picked instead of /bin/bash

### ISSUE THREAD

**Issue by damiendube** [CircleCI-Public/jq-orb#14]
In trying to run the orb circleci/jira that depends on circleci/jq
circleci/jira depends on circleci/jq 1.8.0 but I also tested with circleci/jq 2.0.0

Running on image docker:18.06.3-ce-git, which is based of alpine 3.9.
jq/install fails 
Error message is

sh: 0: unknown operand
/bin/sh: syntax error: unexpected "(" (expecting "fi")

This is due to jq/install using the /bin/sh shell instead of /bin/bash.
I've installed bash prior to running this task and it didn't fix the issue.

**Comment by lokst** [comment]
@damiendube Could you try using a different image that has Bash pre-installed? I believe `jq/install` is using the default shell for your environment (see: https://circleci.com/docs/2.0/configuration-reference/#default-shell-options)

**Comment by damiendube** [comment]
It is working properly if I use an image with a pre-installed bash. What I'm trying to do is have it work on an alpine based image.

**Comment by lokst** [comment]
It looks like running the following before `jq/install` should work, to force /bin/bash to be used, and allow `jq` to be successfully installed:

```
apk add bash
apk add curl
ln -sf /bin/bash /bin/sh
```

Feel free to reopen the issue if it doesn't!
